apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  annotations:
    meta.helm.sh/release-name: observability
    meta.helm.sh/release-namespace: observability
  creationTimestamp: "2024-04-24T20:30:27Z"
  generation: 1
  labels:
    app: kube-prometheus-stack-prometheus
    app.kubernetes.io/instance: observability
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 58.2.2
    chart: kube-prometheus-stack-58.2.2
    heritage: Helm
    release: observability
  name: observability-kube-prometh-prometheus
  namespace: observability
  resourceVersion: "37939"
  uid: cdccea26-3878-44de-9917-d8d38dcfd5ff
spec:
  enableAdminAPI: false
  evaluationInterval: 30s
  externalUrl: http://observability-kube-prometh-prometheus.observability:9090
  hostNetwork: false
  image: quay.io/prometheus/prometheus:v2.51.2
  listenLocal: false
  logFormat: logfmt
  logLevel: info
  paused: false
  podMonitorNamespaceSelector: {}
  podMonitorSelector:
    matchLabels:
      release: observability
  portName: http-web
  probeNamespaceSelector: {}
  probeSelector:
    matchLabels:
      release: observability
  replicas: 1
  retention: 10d
  routePrefix: /
  ruleNamespaceSelector: {}
  ruleSelector:
    matchLabels:
      release: observability
  scrapeConfigNamespaceSelector: {}
  scrapeConfigSelector:
    matchLabels:
      release: observability
  scrapeInterval: 30s
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
  serviceAccountName: observability-kube-prometh-prometheus
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector:
    matchLabels:
      release: observability
  shards: 1
  tsdb:
    outOfOrderTimeWindow: 0s
  version: v2.51.2
  walCompression: true
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-04-24T20:37:09Z"
    message: ""
    observedGeneration: 1
    reason: ""
    status: "True"
    type: Available
  - lastTransitionTime: "2024-04-24T20:37:09Z"
    message: ""
    observedGeneration: 1
    reason: ""
    status: "True"
    type: Reconciled
  paused: false
  replicas: 1
  selector: app.kubernetes.io/instance=observability-kube-prometh-prometheus,app.kubernetes.io/managed-by=prometheus-operator,app.kubernetes.io/name=prometheus,operator.prometheus.io/name=observability-kube-prometh-prometheus,prometheus=observability-kube-prometh-prometheus
  shardStatuses:
  - availableReplicas: 1
    replicas: 1
    shardID: "0"
    unavailableReplicas: 0
    updatedReplicas: 1
  shards: 1
  unavailableReplicas: 0
  updatedReplicas: 1
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: ray-cluster-gcs-rules
  namespace: prometheus-system
  labels:
    # `release: $HELM_RELEASE`: Prometheus can only detect Rule with this label.
    release: prometheus
spec:
  groups:
  - interval: 30s
    name: ray-cluster-main-staging-gcs.rules
    rules:
    - expr: |2
                      (
                        100 * (
                                sum(
                                     rate(
                                           ray_gcs_update_resource_usage_time_bucket{container="ray-head", le="20.0"}[30d]
                                     )
                                )
                                /
                                sum(
                                     rate(
                                           ray_gcs_update_resource_usage_time_count{container="ray-head"}[30d]
                                     )
                                )
                        )
                      )
      record: ray_gcs_availability_30d
    - alert: MissingMetricRayGlobalControlStore
      annotations:
        description: Ray GCS is not emitting any metrics for Resource Update requests
        summary: Ray GCS is not emitting metrics anymore
      expr: |2
                      (
                       absent(ray_gcs_update_resource_usage_time_bucket) == 1
                      )
      for: 5m
      labels:
        severity: critical