name: Create release

on:
  push:
    branches:
      - 'dev'
      - 'main'
jobs:
  draft-and-publish-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Important for release-drafter to get full history

      - name: Dump push event context var JSON
        run: cat $GITHUB_EVENT_PATH

      - name: Draft the release
        id: release-drafter
        uses: release-drafter/release-drafter@v6.1.0
        with:
          publish: true
          include-preleases: ${{ github.ref_name == 'dev'}}
          prerelease: ${{ github.ref_name == 'dev'}}
          prerelease-identifier: 'pre'
          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}